### ISSUE TITLE
Details on xDAI specification

### ISSUE THREAD

**Issue by ArseniiPetrovich** [poanetwork/poa-chain-spec#146]
Hi, Team. I'm working on installing latest forks/EIPs and looking through the commits that changed in this repo on xDAI branch since the network creation. Among others I have discovered the [IstanbulHF commit](https://github.com/poanetwork/poa-chain-spec/commit/cc8181bd20ee2bacde03794ce6a8b05869158c68#diff-42eb5109ad96d4ac46cdcbf18f2938de) that appeared to be not that clear for me. 

I'm particularly interested in the following lines:
```
"divisor": 20
"alt_bn128_const_operations": {
                "price": 500
}
"alt_bn128_const_operations": {
                "price": 150
}
"alt_bn128_const_operations": {
                "price": 40000
}
"alt_bn128_const_operations": {
                "price": 6000
}
"alt_bn128_pairing": {
                "base": 100000,
                "pair": 80000
}
"alt_bn128_pairing": {
                "base": 45000,
                "pair": 34000
}
"blake2_f": {
                "gas_per_round": 1
}
"linear": {
                "base": 3000,
                "word": 0
}
"linear": {
                "base": 60,
                "word": 12
}
"linear": {
                "base": 600,
                "word": 120
}
"linear": {
                "base": 15,
                "word": 3
}
```

What does all this numbers means? Should I include it into my client's network HF? What are your suggestions?
Is there any other EIPs I should include that are not included into xDAI network?

Thanks in advance!

**Comment by varasev** [comment]
If you plan to activate Istanbul HF, you need to do the same changes in your spec. If you need to launch xDai-like chain, you shouldn't activate any other EIPs than those currently activated on xDai.

Regarding the lines above: the Istanbul HF includes [EIP-1108](https://github.com/openethereum/openethereum/commit/a9cb5722383cb89ebf38ba4ea2fa2073f15d5f8b#diff-9fd455e616bdf3d1f497de5491759459) which reduces some costs for some smart contract build-in operations. These costs are defined by the parameters you listed above.

**Comment by ArseniiPetrovich** [comment]
Okay, seems clear for me, thank you! Last question if you don't mind.
I saw [this](https://github.com/poanetwork/poa-chain-spec/issues/123) issue. Do you think I need to active these EIPs as well or is it a bad idea?
@varasev

**Comment by varasev** [comment]
@ArseniiPetrovich We didn't try those on our chains, so I can't recommend activating them, but you can launch some test chain with them and see if there are no issues (before using in production)

**Comment by ArseniiPetrovich** [comment]
> @ArseniiPetrovich We didn't try those on our chains, so I can't recommend activating them, but you can launch some test chain with them and see if there are no issues (before using in production)

Well, we would like to have two networks - test and prod ones, so I'd probably activate those on test only. Thank you for your help!
